// Generated by gencpp from file lejun_jiang_roslab/scan_range.msg
// DO NOT EDIT!


#ifndef LEJUN_JIANG_ROSLAB_MESSAGE_SCAN_RANGE_H
#define LEJUN_JIANG_ROSLAB_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lejun_jiang_roslab
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : header()
    , closest_point(0.0)
    , farthest_point(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , closest_point(0.0)
    , farthest_point(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _closest_point_type;
  _closest_point_type closest_point;

   typedef double _farthest_point_type;
  _farthest_point_type farthest_point;





  typedef boost::shared_ptr< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::lejun_jiang_roslab::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::lejun_jiang_roslab::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::lejun_jiang_roslab::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lejun_jiang_roslab::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lejun_jiang_roslab::scan_range_<ContainerAllocator1> & lhs, const ::lejun_jiang_roslab::scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.closest_point == rhs.closest_point &&
    lhs.farthest_point == rhs.farthest_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lejun_jiang_roslab::scan_range_<ContainerAllocator1> & lhs, const ::lejun_jiang_roslab::scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lejun_jiang_roslab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "492e98f4ad5413e40d76ac2fceece9f6";
  }

  static const char* value(const ::lejun_jiang_roslab::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x492e98f4ad5413e4ULL;
  static const uint64_t static_value2 = 0x0d76ac2fceece9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lejun_jiang_roslab/scan_range";
  }

  static const char* value(const ::lejun_jiang_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 closest_point\n"
"float64 farthest_point\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lejun_jiang_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.closest_point);
      stream.next(m.farthest_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lejun_jiang_roslab::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lejun_jiang_roslab::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "closest_point: ";
    Printer<double>::stream(s, indent + "  ", v.closest_point);
    s << indent << "farthest_point: ";
    Printer<double>::stream(s, indent + "  ", v.farthest_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEJUN_JIANG_ROSLAB_MESSAGE_SCAN_RANGE_H
